version: '3'
services:
  #Data visualizer
  chronograf:
    image: chronograf:alpine
    command: --influxdb-url=http://influxdb:8086
    ports: ["8888:8888"]

  #Data store
  influxdb:
    image: influxdb:alpine
    ports: ["8086:8086"]
    environment:
      - INFLUXDB_DB=telemetry
      - INFLUXDB_ADMIN_PASSWORD=admin

  #pipeline data collector
  pipeline-gnmi:
    image: yohanpipereau/pipeline-gnmi
    depends_on:
      - vpp1
    environment:
      #[vpp1] section
      - PIPELINE_vpp1_stage=xport_input
      - PIPELINE_vpp1_type=gnmi
      - PIPELINE_vpp1_server=172.100.10.101:50051
      - PIPELINE_vpp1_path1=/if/rx@1
      - PIPELINE_vpp1_tls=false
      - PIPELINE_vpp1_username=cisco
      - PIPELINE_vpp1__password=cisco
      #[vpp2] section
      - PIPELINE_vpp2_stage=xport_input
      - PIPELINE_vpp2_type=gnmi
      - PIPELINE_vpp2_server=172.100.10.102:50051
      - PIPELINE_vpp2_path1=/if/tx@1
      - PIPELINE_vpp2_tls=false
      - PIPELINE_vpp2_username=cisco
      - PIPELINE_vpp2__password=cisco
      #[metrics] section to send to influx
      - PIPELINE_metrics_stage=xport_output
      - PIPELINE_metrics_type=metrics
      - PIPELINE_metrics_output=influx
      - PIPELINE_metrics_influx=http://influxdb:8086
        #It is not used but need to be passed:
      - PIPELINE_metrics_file=/etc/pipeline/metrics.json
      - PIPELINE_metrics_database=telemetry
      - PIPELINE_metrics_username=admin
      - PIPELINE_metrics__password=admin
      - PIPELINE_metrics_dump=influxdump.txt #data sent to influx
    networks:
      default:

      telemetry:
        ipv4_address: 172.100.10.100

  #VPP instance working with gNMI server
  vpp1:
    image: yohanpipereau/vpp-gnmi
    command: -f
    privileged: true
    ports: ["50051:50051", "8301:2831", "4431:8445"] #gRPC server port
    networks:
      default:

      telemetry:
        ipv4_address: 172.100.10.101

      node1_node2:
        ipv4_address: 172.100.12.101

  vpp2:
    image: yohanpipereau/vpp-gnmi
    command: -f
    privileged: true
    ports: ["50052:50051", "8302:2831", "4432:8445"] #gRPC server port
    networks:
      default:

      telemetry:
        ipv4_address: 172.100.10.102

      node1_node2:
        ipv4_address: 172.100.12.102

networks:
  default:

  telemetry:
    ipam:
      config:
        - subnet: 172.100.10.0/24

  node1_node2:
    ipam:
      config:
        - subnet: 172.100.12.0/24
